# -*- coding: utf-8 -*-
"""sheet_csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dx2ax0zPr14NwKBgFmjyb-aNQAx09C89
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
np.set_printoptions(suppress = True)
import glob
import xlrd
from pandas import DataFrame
import os
from openpyxl import load_workbook

file_path = r'/content/drive/MyDrive/xyc_composite_result'
excel_names = glob.glob(rf'{file_path}/*.xlsx')
result = []

path=excel_names#delet later
for path in excel_names:#run later
  sheets = xlrd.open_workbook(path).sheet_names()

  # name = sheets[0]

  data = np.dstack(pd.read_excel(path,sheet_name = name) for name in sheets)#Read excel in a circular format, stacking all reads together

  size = np.shape(data)
  print(size)

  data[np.isnan(data)] = 0
  data

  for i in range(size[0]):
    for j in range(size[1]):
      if data[i,j,0] > 0 and data[i,j,0] < 10000:
        result.append(data[i,j,:])
df = pd.DataFrame(result,columns = sheets)

df.to_csv(rf'/content/drive/MyDrive/xyc_composite_finalresult/{path[-9:-5]}.csv',index = None)

# file_path = r'/content/drive/MyDrive/xyc_composite_result'
# excel_names = glob.glob(rf'{file_path}/*.xlsx')

# sheets = xlrd.open_workbook(path).sheet_names()

# def func(path):
#   result = []
#   data = np.dstack(pd.read_excel(path,sheet_name = name) for name in sheets)
#   size = np.shape(data)
#   data[np.isnan(data)] = 0
#   for i in range(size[0]):
#     for j in range(size[1]):
#       if data[i,j,0] > 0 and data[i,j,0] < 10000:
#         result.append(data[i,j,:])
#   return result
# for path in excel_names:
#   result = func(path)
#   df = pd.DataFrame(result,columns = sheets)
#   df.to_csv(rf'/content/drive/MyDrive/xyc_composite_finalresult/{path[-9:-5]}.csv',index = None)